### ISSUE TITLE
i386 installation failure due to ASM

### ISSUE THREAD

**Issue by TomMD** [A1kmm/hs-bcrypt#6]
It appears begriffs/postgrest#129 is an i386 bug with bcrypt.   I see you disabled ASM for allbut the i386 case.  In that case there exists a macro `BF_body() ~~> _BF_body_r()`.  However, I suspect the `_BF_body_r()` was deleted from this repo.  Suggestion: don't define `BF_ASM` when on i386 or any other platform.

**Comment by TomMD** [comment]
I notice the pull request, #4, addresses exactly this and has lingered since October.  Suppose the maintainer checks e-mails and not github?  Lets see...

**Comment by A1kmm** [comment]
Fixed in version 0.0.6.
